version: "3"
services:
    gitserver:
        volumes:
            - './ssl:/etc/nginx/ssl'
            - './git:/git'
            - './.htpasswd:/.htpasswd'
        ports:
            - '8443:443'
        image: alexivkin/gitserver:1.0
        build: .
